### ISSUE TITLE
HTTP: 500 Internal Server Error

### ISSUE THREAD

**Issue by stonerl** [shred/flattr4j#5]
I'm using [AntennaPod](https://github.com/AntennaPod/AntennaPod/) and they use the flattr4j api. I stumbled upon an [error](https://github.com/AntennaPod/AntennaPod/issues/1943). When I flattr something I get an HTTP 500 error. But hen I check my flattr page, the flattr was successful.

Here is the log:
```
05-23 22:40:01.796 W/System.err(23004): org.shredzone.flattr4j.exception.FlattrException: HTTP 500: Internal Server Error
```

**Comment by shred** [comment]
I tested it right now, and I was able to flattr via flattr4j and get a valid response.

Can you enable flattr4j debug logging and try again?

`adb shell setprop log.tag.flattr4j VERBOSE`

In the debug log, the conversation with the flattr server is shown. Maybe it will give a hint about what is wrong.

**Comment by stonerl** [comment]
I tested it again and the error is gone. Apparently it was an error on flattr's side. But thank you very much for your reply. Closing this one.
